extends Node2D
var test_adv = preload("res://templates/test_adventurer.tscn")
var test_item = preload("res://data/items/pitchfork.tres")
@onready var door_player : AudioStreamPlayer = $AudioStreamPlayer
func _ready() -> void:
	#var adv : Adventurer = test_adv.instantiate() as Adventurer
	#Guild.register_guild_member(adv)
	var lst = Quest.list
	var quest : Quest = Quest.list[1].duplicate(true)
	quest.setup()
	Guild.add_quest(quest)
	Guild.assign_quest(Game.player.data, quest)
	var itm = test_item.duplicate()
	Game.player.data.pickup_item(itm)
	Game.player.data.move_item(Vector2(0,0), Vector2(1,0))
	#Game.end_shift()
	#var tween = create_tween()
	#tween.tween_interval(3)
	#tween.tween_callback(Callable($DoorLight/AnimationPlayer.play).bind("open"))
	#tween.tween_callback(play_door)
	#tween.tween_interval(.25)
	#tween.tween_property(Game.player, "visible", true, 0)
	#tween.tween_interval(.5)
	#tween.tween_callback(Dialogic.start.bind("res://dialogic/timelines/intro.dtl"))

func play_door() -> void:
	door_player.play()
