class_name Guildhall extends Node2D

var employees : Dictionary[String, GuildEmployee] = {}
var interactables : Dictionary[String, Interactable] = {}
var board : QuestBoard
@onready var sprite_node : Node2D = $Sprites
@onready var nav_region : NavigationRegion2D = $RoomRegion

func _ready() -> void:
	Guild.hall = self
	for child in sprite_node.get_children():
		if child is GuildEmployee:
			register_employee(child)


func register_employee(employee: GuildEmployee) -> void:
	employees[employee.name] = employee

func register_interactables(equipment: Interactable) -> void:
	interactables[equipment.name] = equipment

func add_sprite(sprite : AdventurerSprite) -> void:
	sprite_node.add_child(sprite)
