extends Control

var superquitting: bool = false

func show_quit_confirm() -> void:
	$ConfirmationDialog.popup_centered()

func _on_back_button_pressed() -> void:
	queue_free()

func _on_quit_button_pressed() -> void:
	superquitting = false
	show_quit_confirm()
	pass # Replace with function body.


func _on_superquit_button_pressed() -> void:
	superquitting = true
	show_quit_confirm()
	pass # Replace with function body.


func _on_confirmation_dialog_confirmed() -> void:
	Game.test_save()
	queue_free()
	if superquitting:
		get_tree().quit()
	else:
		Game.switch_scenes("start_menu")
